name: flutter_runtime_env
description: Checks if Analytics should be enabled by looking at
  various different parameters
version: 0.0.1
homepage: https://gitjournal.io

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.gitjournal.flutter_runtime_env
    pluginClass: FlutterRuntimeEnvPlugin
